language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install -D
  - pnpm install -g chrome-webstore-upload-cli
jobs:
  include:
    - stage: "Tests"
      name: "Lint"
      script: pnpm run lint
deploy:
  - provider: script
    script: npm run pack; npm run publish;
    on:
      branch: master
